# Filtering for SACAIR runs to capture results

In [1]:
import logging
from pathlib import Path

#locals
# from code.run_types import ResSet, RunRes
import pandas as pd

from src.resulting import RESULTS_DIR, load_config_and_find_runs, print_json
from src.run_types import GenInfo


def load_find(conf_path: Path) -> GenInfo:
    runs =  load_config_and_find_runs(
            conf_path,
            exclude=exclude_keys,
            extra_mods=additional_modifications,
            logging_level=logging.DEBUG
        )
    assert runs is not None
    return runs

In [2]:
acc_cuttoff = 0
avail_models = ["MViTv2_S", "MViTv2_S_16x4", "MViTv2_B_32x3", "MViTv2_S_e",]

additional_modifications = {
    "results": {"best_val_acc": lambda x: x > acc_cuttoff},
    "admin": {"model": lambda x: x in avail_models},
    "scheduler": lambda x: x is None
}

exclude_keys = [
    ["results", "test_shuff"],
    ["results", "check_name"],
]

In [ ]:
from collections.abc import Callable
from typing import Any


def _unpack_filters(filters: dict) -> tuple[list[list[str]], list[Callable[[Any], bool]]]:

    filter_key_sets: list[list[str]] = []
    criterions: list[Callable[[Any], bool]] = []
    
    for key, value in filters.items():
        key_set = [key]
        if isinstance(value, Callable):
            criterions.append(value)
            filter_key_sets.append(key_set) 
            continue
            
        elif isinstance(value, dict):
            sub_key_sets, crits =  _unpack_filters(value)
            for sublist in sub_key_sets:
                filter_key_sets.append(key_set + sublist)
            
            criterions.extend(crits)
        else:
            raise TypeError(f'value should be dict or Callable, instead got: {type(value)}')
        

    return filter_key_sets, criterions

In [16]:
filter_key_sets, criterions = _unpack_filters(additional_modifications)
print(filter_key_sets)
print(len(filter_key_sets) == len(criterions))

[['results', 'best_val_acc'], ['admin', 'model'], ['scheduler']]
True

In [ ]:
def _pop_keys(d: dict, keys: list[Any], default = None) -> dict:
    if len(keys) == 1:
        return d.pop(keys[0], default)
    
    parent = d
    for key in keys[:-1]:
        parent = parent[key]

    return parent.pop(keys[-1], default)


def _drop_keys(d: dict, keys: list[Any]) -> dict:
    """Drop a nested value from a dict and return the dict. 

    Args:
        d (dict): A dictionary to modify in place
        keys (list[Any]): List of keys in order to index. 

    Returns:
        dict: The reference the original dictionary
    """
    
    parent = d
    for key in keys[:-1]:
        parent = parent[key]

    parent.pop(keys[-1])
    
    return d

In [31]:
d = {str(i): x for i in range(ord('a'), ord('e')) for x in range(5)}
e = {x : str(i) for i in range(ord('a'), ord('e')) for x in range(5)}
y = {'D': d, 'E': e}
print(y)

{'D': {'97': 4, '98': 4, '99': 4, '100': 4}, 'E': {0: '100', 1: '100', 2: '100', 3: '100', 4: '100'}}

In [32]:
print(_drop_keys(y, ['D']))

{'E': {0: '100', 1: '100', 2: '100', 3: '100', 4: '100'}}

In [33]:
print(y)

{'E': {0: '100', 1: '100', 2: '100', 3: '100', 4: '100'}}

In [17]:
results_dir = RESULTS_DIR / 'sacair_2026'
runs_16_p = results_dir / 'config_16f_15p.toml'
runs_32_p = results_dir / 'config_32f_15p.toml'
assert runs_16_p.exists(), f"{runs_16_p} not found"
assert runs_32_p.exists(), f"{runs_32_p} not found"

## Parameters in common:

The only parameter that differs is the number of frames. In all cases, models trained on asl300 upward were initialised from the previous split.

In [19]:
runs_16 = load_find(runs_16_p)
runs_32 = load_find(runs_32_p)

DEBUG resulting: {
    "training": {
        "batch_size_equivalent": 8
    },
    "optimizer": {
        "eps": 1e-05,
        "backbone_init_lr": 0.0001,
        "backbone_weight_decay": 0.001,
        "classifier_init_lr": 0.001,
        "classifier_weight_decay": 0.001
    },
    "model_params": {
        "drop_p": 0.5
    },
    "data": {
        "strict_size": true,
        "target_length": 16,
        "frame_size": 224,
        "train_augs": {
            "normalise": true,
            "temporal_aug": [
                {
                    "target_length": 16,
                    "max_wobble": 0,
                    "type": "og",
                    "randomise": false
                }
            ],
            "spatial_aug": [
                {
                    "frame_size": 224,
                    "type": "Random_crop"
                },
                {
                    "type": "HORIZONTAL_FLIP",
                    "p": 0.5
                }
            ]
        },
        "test_augs": {
            "normalise": true,
            "temporal_aug": [
                {
                    "target_length": 16,
                    "max_wobble": 0,
                    "type": "og",
                    "randomise": false
                }
            ],
            "spatial_aug": [
                {
                    "frame_size": 224,
                    "type": "Centre_crop"
                }
            ]
        }
    },
    "stopping": {
        "metric": "loss",
        "phase": "val",
        "mode": "min",
        "min_delta": 0.01,
        "patience": 15
    }
}
INFO resulting: Loaded que state from /home/luke/Code/SLR/src/que/Runs.json
DEBUG resulting: value mismatch: search=1.1030668480887442e-06, spec=1e-05
DEBUG resulting: value mismatch: search=2.2189956725779973e-05, spec=1e-05
DEBUG resulting: value mismatch: search=5.269835668073251e-07, spec=1e-05
DEBUG resulting: value mismatch: search=6.71732498962368e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.026331429500054e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.1240346418713265e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.222407231126328e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.0762096220158002e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.1284196148156047e-06, spec=1e-05
DEBUG resulting: value mismatch: search=4.1106503111231215e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.677191186769711e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.5114016489393324e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.0157925494399704e-06, spec=1e-05
DEBUG resulting: value mismatch: search=5.50501303176689e-07, spec=1e-05
DEBUG resulting: value mismatch: search=2.95287373383809e-06, spec=1e-05
DEBUG resulting: value mismatch: search=2.4291638023944724e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.1886409610465574e-06, spec=1e-05
DEBUG resulting: value mismatch: search=3.147919586796423e-05, spec=1e-05
DEBUG resulting: value mismatch: search=6.1047408769173805e-06, spec=1e-05
DEBUG resulting: value mismatch: search=6.728775054375206e-07, spec=1e-05
DEBUG resulting: value mismatch: search=2.395245861206789e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.00010850070749880376, spec=1e-05
DEBUG resulting: value mismatch: search=1.1049723690779427e-05, spec=1e-05
DEBUG resulting: value mismatch: search=5.807117822738859e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.8264384861503377e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.00014711390136605684, spec=1e-05
DEBUG resulting: value mismatch: search=2.801717904817226e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.0006276421222698809, spec=1e-05
DEBUG resulting: value mismatch: search=0.00044263316616341875, spec=1e-05
DEBUG resulting: value mismatch: search=0.0006942868653492514, spec=1e-05
DEBUG resulting: value mismatch: search=1.4028721732069292e-06, spec=1e-05
DEBUG resulting: value mismatch: search=3.761377874084025e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.0001189172979692074, spec=1e-05
DEBUG resulting: value mismatch: search=3.927353142332758e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.532606508806105e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.0424696201631964e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.0755505606244228e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.11436882520121e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.0003888472971188119, spec=1e-05
DEBUG resulting: value mismatch: search=0.00024105316678679488, spec=1e-05
DEBUG resulting: value mismatch: search=4.617028959255292e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.0001359869599401483, spec=1e-05
DEBUG resulting: value mismatch: search=2.118051490509395e-06, spec=1e-05
DEBUG resulting: value mismatch: search=7.447416068559313e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.9365933029432142e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.932944260118881e-05, spec=1e-05
DEBUG resulting: value mismatch: search=5.113025379776558e-06, spec=1e-05
DEBUG resulting: value mismatch: search=5.772780002567584e-07, spec=1e-05
DEBUG resulting: value mismatch: search=0.000724104959781741, spec=1e-05
DEBUG resulting: value mismatch: search=1.4232491015213249e-05, spec=1e-05
DEBUG resulting: value mismatch: search=4.066450251658927e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.4464392545123695e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.3642267516798524e-05, spec=1e-05
DEBUG resulting: value mismatch: search=9.281763000230091e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.9703360479925597e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.0008161393223922246, spec=1e-05
DEBUG resulting: value mismatch: search=0.00011481846249903044, spec=1e-05
DEBUG resulting: value mismatch: search=0.0009375019239540688, spec=1e-05
DEBUG resulting: value mismatch: search=4.4823725178679185e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.677107646071362e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.0005053605238808797, spec=1e-05
DEBUG resulting: value mismatch: search=3.6885504548943615e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.0001934669190549208, spec=1e-05
DEBUG resulting: value mismatch: search=5.005080513808999e-05, spec=1e-05
DEBUG resulting: value mismatch: search=9.78937714006801e-07, spec=1e-05
DEBUG resulting: value mismatch: search=1.2539666000505602e-05, spec=1e-05
DEBUG resulting: value mismatch: search=4.164778813483827e-06, spec=1e-05
DEBUG resulting: value mismatch: search=5.901340093725284e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.8057912241848076e-06, spec=1e-05
DEBUG resulting: value mismatch: search=6.036872885202408e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.00010934789933970891, spec=1e-05
DEBUG resulting: value mismatch: search=7.95558214526238e-07, spec=1e-05
DEBUG resulting: value mismatch: search=3.593152577613672e-05, spec=1e-05
DEBUG resulting: value mismatch: search=8.115611642049519e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.0015806724195533551, spec=1e-05
DEBUG resulting: value mismatch: search=1.1628577508183356e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.00013993941999513107, spec=1e-05
DEBUG resulting: value mismatch: search=1.8639514609664984e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.002614326965056252, spec=1e-05
DEBUG resulting: value mismatch: search=5.697734853701029e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.507577733443675e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.5818006771887596e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.00017257571642654803, spec=1e-05
DEBUG resulting: value mismatch: search=8.391092749325685e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.5668476060016098e-05, spec=1e-05
DEBUG resulting: value mismatch: search=3.875249661883351e-06, spec=1e-05
DEBUG resulting: value mismatch: search=4.3252035337871625e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.00022005162406777372, spec=1e-05
DEBUG resulting: value mismatch: search=7.922178281108937e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.0005045758541364307, spec=1e-05
DEBUG resulting: value mismatch: search=1.2757952294604055e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.5098350399655945e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.0008163369278602752, spec=1e-05
DEBUG resulting: value mismatch: search=3.629615004578392e-05, spec=1e-05
DEBUG resulting: value mismatch: search=6.372448689706732e-06, spec=1e-05
DEBUG resulting: value mismatch: search=5.722184835375822e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.6168233305539413e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.7102861010556482e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.0017169868768282925, spec=1e-05
DEBUG resulting: value mismatch: search=0.0005280483175930969, spec=1e-05
DEBUG resulting: value mismatch: search=4.869264301820606e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.0991929994719892e-05, spec=1e-05
DEBUG resulting: value mismatch: search=8.47799602962149e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.1732972441677123e-06, spec=1e-05
DEBUG resulting: value mismatch: search=8.381692272484083e-07, spec=1e-05
DEBUG resulting: value mismatch: search=1.2221052018243583e-06, spec=1e-05
DEBUG resulting: value mismatch: search=7.646176431208243e-07, spec=1e-05
DEBUG resulting: value mismatch: search=0.0008833264484149185, spec=1e-05
DEBUG resulting: value mismatch: search=2.574122745336235e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.0018024055805625876, spec=1e-05
DEBUG resulting: value mismatch: search=1.210050124933524e-06, spec=1e-05
DEBUG resulting: value mismatch: search=5.734296205870243e-07, spec=1e-05
DEBUG resulting: value mismatch: search=1.251325587990918e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.0019091165627190736, spec=1e-05
DEBUG resulting: value mismatch: search=3.683408069774317e-06, spec=1e-05
DEBUG resulting: value mismatch: search=8.44620651149438e-06, spec=1e-05
DEBUG resulting: value mismatch: search=4.1159401619606485e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.1734300457675815e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.004531374407873184, spec=1e-05
DEBUG resulting: value mismatch: search=7.325280458904712e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.4222728770964217e-05, spec=1e-05
DEBUG resulting: value mismatch: search=4.858032620179882e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.00045342121032384647, spec=1e-05
DEBUG resulting: value mismatch: search=7.274819959964253e-06, spec=1e-05
DEBUG resulting: value mismatch: search=3.9900749125461114e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.682326183517198e-06, spec=1e-05
DEBUG resulting: value mismatch: search=5.2285108970384215e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.881909276269284e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.4850131804877348e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.000184676665154022, spec=1e-05
DEBUG resulting: value mismatch: search=2.9992558890082245e-06, spec=1e-05
DEBUG resulting: value mismatch: search=2.3819426223464875e-05, spec=1e-05
DEBUG resulting: value mismatch: search=3.33181252811212e-05, spec=1e-05
DEBUG resulting: value mismatch: search=4.579280325490592e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.005583936684726057, spec=1e-05
DEBUG resulting: value mismatch: search=2.0003727863512956e-06, spec=1e-05
DEBUG resulting: value mismatch: search=9.65554267810338e-07, spec=1e-05
DEBUG resulting: value mismatch: search=5.222231584477699e-06, spec=1e-05
DEBUG resulting: value mismatch: search=9.202738262790423e-06, spec=1e-05
DEBUG resulting: value mismatch: search=4.265286856046604e-05, spec=1e-05
DEBUG resulting: value mismatch: search=5.259100872560702e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.7856706063957357e-05, spec=1e-05
DEBUG resulting: value mismatch: search=3.767957159834892e-06, spec=1e-05
DEBUG resulting: value mismatch: search=3.9921350201117624e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.6269194290350766e-06, spec=1e-05
DEBUG resulting: value mismatch: search=2.2431979518345103e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.246637223389464e-05, spec=1e-05
DEBUG resulting: value mismatch: search=3.657171242205195e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.0001702938109265036, spec=1e-05
DEBUG resulting: value mismatch: search=1.6292220178125845e-06, spec=1e-05
DEBUG resulting: value mismatch: search=5.445301242455613e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.5649314915732211e-06, spec=1e-05
DEBUG resulting: value mismatch: search=5.5828022952535395e-05, spec=1e-05
DEBUG resulting: value mismatch: search=4.745565856689056e-06, spec=1e-05
DEBUG resulting: value mismatch: search=8.603703770199714e-06, spec=1e-05
DEBUG resulting: value mismatch: search=7.285616350930742e-07, spec=1e-05
DEBUG resulting: value mismatch: search=1.7728427829692225e-06, spec=1e-05
DEBUG resulting: value mismatch: search=9.311831738825206e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.5793773346684865e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.0011045871383020725, spec=1e-05
DEBUG resulting: value mismatch: search=8.47596674358946e-07, spec=1e-05
DEBUG resulting: value mismatch: search=1.8577431417892233e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.6689630324328196e-05, spec=1e-05
DEBUG resulting: value mismatch: search=4.567886449120126e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.2333000171667502e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.3086786188568069e-06, spec=1e-05
DEBUG resulting: value mismatch: search=2.9967286068331153e-05, spec=1e-05
DEBUG resulting: value mismatch: search=4.123600883678095e-06, spec=1e-05
DEBUG resulting: value mismatch: search=6.889558809418501e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.00031311928287500515, spec=1e-05
DEBUG resulting: value mismatch: search=3.712948796868334e-06, spec=1e-05
DEBUG resulting: value mismatch: search=4.7987247553865355e-06, spec=1e-05
DEBUG resulting: value mismatch: search=2.6258488530499926e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.882213128720634e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.003661594681008381, spec=1e-05
DEBUG resulting: value mismatch: search=0.001221651757339674, spec=1e-05
DEBUG resulting: value mismatch: search=9.451471100555764e-07, spec=1e-05
DEBUG resulting: value mismatch: search=0.0008168675026181008, spec=1e-05
DEBUG resulting: value mismatch: search=2.760658899209696e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.1649680738917582e-05, spec=1e-05
DEBUG resulting: value mismatch: search=9.453307820859245e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.005523432813390122, spec=1e-05
DEBUG resulting: value mismatch: search=5.325128494099104e-05, spec=1e-05
DEBUG resulting: value mismatch: search=7.317563289501665e-07, spec=1e-05
DEBUG resulting: value mismatch: search=1.8940839218158664e-06, spec=1e-05
DEBUG resulting: value mismatch: search=4.257351670120121e-05, spec=1e-05
DEBUG resulting: value mismatch: search=7.966657154395955e-07, spec=1e-05
DEBUG resulting: value mismatch: search=1.9516556443398007e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.327862462829772e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.4062566666459976e-06, spec=1e-05
DEBUG resulting: value mismatch: search=2.406842917810983e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.7217564946996043e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.0343166028120669e-05, spec=1e-05
DEBUG resulting: value mismatch: search=4.763294888344376e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.3994566744426533e-06, spec=1e-05
DEBUG resulting: value mismatch: search=1.589902648122232e-05, spec=1e-05
DEBUG resulting: value mismatch: search=8.932802770670852e-07, spec=1e-05
DEBUG resulting: value mismatch: search=9.881197770660704e-05, spec=1e-05
DEBUG resulting: value mismatch: search=2.930715776163428e-05, spec=1e-05
DEBUG resulting: value mismatch: search=3.4668022943554575e-05, spec=1e-05
DEBUG resulting: value mismatch: search=5.540064642744089e-06, spec=1e-05
DEBUG resulting: value mismatch: search=4.64460308721673e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.8571501425005465e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.334185049366311e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.00033132828651462565, spec=1e-05
DEBUG resulting: value mismatch: search=1.536997290759322e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.00036413537458650675, spec=1e-05
DEBUG resulting: value mismatch: search=3.657297206514687e-06, spec=1e-05
DEBUG resulting: value mismatch: search=3.8814253629524885e-05, spec=1e-05
DEBUG resulting: value mismatch: search=5.5990479095837774e-05, spec=1e-05
DEBUG resulting: value mismatch: search=1.4048897833771753e-06, spec=1e-05
DEBUG resulting: value mismatch: search=2.880753032587694e-05, spec=1e-05
DEBUG resulting: value mismatch: search=6.015097875784863e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.00021299027025844424, spec=1e-05
DEBUG resulting: value mismatch: search=5.132447317986739e-07, spec=1e-05
DEBUG resulting: value mismatch: search=5.619886383141765e-06, spec=1e-05
DEBUG resulting: value mismatch: search=7.694405838230531e-05, spec=1e-05
DEBUG resulting: value mismatch: search=5.199266881943229e-05, spec=1e-05
DEBUG resulting: value mismatch: search=5.366337792964055e-06, spec=1e-05
DEBUG resulting: value mismatch: search=2.5264046316936044e-06, spec=1e-05
DEBUG resulting: value mismatch: search=3.320169054145765e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.0025716621625505296, spec=1e-05
DEBUG resulting: value mismatch: search=0.004294080583553461, spec=1e-05
DEBUG resulting: value mismatch: search=2.7062108161447387e-06, spec=1e-05
DEBUG resulting: value mismatch: search=8.411144577227919e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.000842416471718599, spec=1e-05
DEBUG resulting: value mismatch: search=9.842047421944286e-05, spec=1e-05
DEBUG resulting: value mismatch: search=7.81397312383894e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.00982952406287817, spec=1e-05
DEBUG resulting: value mismatch: search=1.436185931926626e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.0007884136352004136, spec=1e-05
DEBUG resulting: value mismatch: search=0.00010329612298801574, spec=1e-05
DEBUG resulting: value mismatch: search=0.0038734713376485817, spec=1e-05
DEBUG resulting: value mismatch: search=0.0002238715133349681, spec=1e-05
DEBUG resulting: value mismatch: search=0.0024979365048216824, spec=1e-05
DEBUG resulting: value mismatch: search=8.041024866286437e-06, spec=1e-05
DEBUG resulting: value mismatch: search=3.51010248810355e-05, spec=1e-05
DEBUG resulting: value mismatch: search=5.748356625328888e-07, spec=1e-05
DEBUG resulting: value mismatch: search=1.624229716950072e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.008276925771089728, spec=1e-05
DEBUG resulting: value mismatch: search=1.945257665392239e-06, spec=1e-05
DEBUG resulting: value mismatch: search=2.2315358411598923e-06, spec=1e-05
DEBUG resulting: value mismatch: search=7.735968702870497e-05, spec=1e-05
DEBUG resulting: value mismatch: search=0.007864565001404823, spec=1e-05
DEBUG resulting: value mismatch: search=5.3790909656979704e-06, spec=1e-05
DEBUG resulting: value mismatch: search=0.0006105569970778522, spec=1e-05

## Runs 16 frames:

Lets check how many runs there are that match that spec:

In [20]:
for run in runs_16['results']:
    print_json(run['admin'])
    print()
print(len(runs_16['results']))

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl2000",
    "save_path": "/home/luke/Code/SLR/src/runs/asl2000/S3D/exp049/checkpoints",
    "seed": 42,
    "exp_no": "049",
    "recover": false,
    "config_path": "/home/luke/Code/SLR/src/results/satnac_2026/S3D/config_16f_15p.toml",
    "weight_path": "/home/luke/Code/SLR/src/runs/asl1000/S3D/exp048/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl1000",
    "save_path": "/home/luke/Code/SLR/src/runs/asl1000/S3D/exp048/checkpoints",
    "seed": 42,
    "exp_no": "048",
    "recover": false,
    "config_path": "/home/luke/Code/SLR/src/results/satnac_2026/S3D/config_16f_15p.toml",
    "weight_path": "/home/luke/Code/SLR/src/runs/asl300/S3D/exp047/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl300",
    "save_path": "/home/luke/Code/SLR/src/runs/asl300/S3D/exp047/checkpoints",
    "seed": 42,
    "exp_no": "047",
    "recover": false,
    "config_path": "/home/luke/Code/SLR/src/results/satnac_2026/S3D/config_16f_15p.toml",
    "weight_path": "/home/luke/Code/SLR/src/runs/asl100/S3D/exp087/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "/home/luke/Code/SLR/src/runs/asl100/S3D/exp087/checkpoints",
    "seed": 42,
    "exp_no": "087",
    "recover": false,
    "config_path": "/home/luke/Code/SLR/src/results/satnac_2026/S3D/config_16f_15p.toml",
    "weight_path": null
}

{
    "model": "MViTv2_S_16x4",
    "dataset": "WLASL",
    "split": "asl2000",
    "save_path": "runs/asl2000/MViTv2_S_16x4/exp001/checkpoints",
    "seed": 42,
    "exp_no": "001",
    "recover": false,
    "config_path": "configfiles/asl2000/MViTv2_S_16x4/exp001.toml",
    "weight_path": null
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl2000",
    "save_path": "runs/asl2000/S3D/exp001/checkpoints",
    "seed": 42,
    "exp_no": "001",
    "recover": false,
    "config_path": "configfiles/asl2000/S3D/exp001.toml",
    "weight_path": "runs/asl1000/S3D/exp001/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl1000",
    "save_path": "runs/asl1000/S3D/exp001/checkpoints",
    "seed": 42,
    "exp_no": "001",
    "recover": false,
    "config_path": "configfiles/asl1000/S3D/exp001.toml",
    "weight_path": "runs/asl300/S3D/exp003/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl300",
    "save_path": "runs/asl300/S3D/exp003/checkpoints",
    "seed": 42,
    "exp_no": "003",
    "recover": false,
    "config_path": "configfiles/asl300/S3D/exp003.toml",
    "weight_path": "runs/asl100/S3D/exp075/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/S3D/exp075/checkpoints",
    "seed": 42,
    "exp_no": "075",
    "recover": false,
    "config_path": "configfiles/asl100/S3D/exp075.toml",
    "weight_path": null
}

{
    "model": "MViTv2_S_16x4",
    "dataset": "WLASL",
    "split": "asl2000",
    "save_path": "runs/asl2000/MViTv2_S_16x4/exp000/checkpoints",
    "seed": 42,
    "exp_no": "000",
    "recover": true,
    "config_path": "configfiles/asl2000/MViTv2_S_16x4/exp000.toml",
    "weight_path": "runs/asl1000/MViTv2_S_16x4/exp000/checkpoints/best.pth"
}

{
    "model": "MViTv2_S_16x4",
    "dataset": "WLASL",
    "split": "asl1000",
    "save_path": "runs/asl1000/MViTv2_S_16x4/exp000/checkpoints",
    "seed": 42,
    "exp_no": "000",
    "recover": false,
    "config_path": "configfiles/asl1000/MViTv2_S_16x4/exp000.toml",
    "weight_path": "runs/asl300/MViTv2_S_16x4/exp000/checkpoints/best.pth"
}

{
    "model": "MViTv2_S_16x4",
    "dataset": "WLASL",
    "split": "asl300",
    "save_path": "runs/asl300/MViTv2_S_16x4/exp000/checkpoints",
    "seed": 42,
    "exp_no": "000",
    "recover": false,
    "config_path": "configfiles/asl300/MViTv2_S_16x4/exp000.toml",
    "weight_path": "runs/asl100/MViTv2_S_16x4/exp003/checkpoints/best.pth"
}

{
    "model": "MViTv2_S_16x4",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/MViTv2_S_16x4/exp003/checkpoints",
    "seed": 42,
    "exp_no": "003",
    "recover": false,
    "config_path": "configfiles/asl100/MViTv2_S_16x4/exp003.toml",
    "weight_path": null
}

{
    "model": "MViTv2_S_16x4",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/MViTv2_S_16x4/exp000/checkpoints",
    "seed": 42,
    "exp_no": "000",
    "recover": false,
    "config_path": "configfiles/asl100/MViTv2_S_16x4/exp000.toml",
    "weight_path": null
}

14

## Runs 32 frames:

Lets check how many runs there are that match that spec:

<!-- Note there were 3 extra asl100s. We will take exp007 because it is used as a starting point for the asl300 run -->

In [21]:
# runs_32['results'] = runs_32['results'][:-3] 
for run in runs_32['results']:
    print_json(run['admin'])
    print()
print(len(runs_32['results']))

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl2000",
    "save_path": "/home/luke/Code/SLR/src/runs/asl2000/S3D/exp050/checkpoints",
    "seed": 42,
    "exp_no": "050",
    "recover": false,
    "config_path": "/home/luke/Code/SLR/src/results/satnac_2026/S3D/config_32f_15p.toml",
    "weight_path": "/home/luke/Code/SLR/src/runs/asl1000/S3D/exp049/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl1000",
    "save_path": "/home/luke/Code/SLR/src/runs/asl1000/S3D/exp049/checkpoints",
    "seed": 42,
    "exp_no": "049",
    "recover": false,
    "config_path": "/home/luke/Code/SLR/src/results/satnac_2026/S3D/config_32f_15p.toml",
    "weight_path": "/home/luke/Code/SLR/src/runs/asl300/S3D/exp048/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl300",
    "save_path": "/home/luke/Code/SLR/src/runs/asl300/S3D/exp048/checkpoints",
    "seed": 42,
    "exp_no": "048",
    "recover": false,
    "config_path": "/home/luke/Code/SLR/src/results/satnac_2026/S3D/config_32f_15p.toml",
    "weight_path": "/home/luke/Code/SLR/src/runs/asl100/S3D/exp088/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "/home/luke/Code/SLR/src/runs/asl100/S3D/exp088/checkpoints",
    "seed": 42,
    "exp_no": "088",
    "recover": false,
    "config_path": "/home/luke/Code/SLR/src/results/satnac_2026/S3D/config_32f_15p.toml",
    "weight_path": null
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl2000",
    "save_path": "runs/asl2000/MViTv2_B_32x3/exp004/checkpoints",
    "seed": 42,
    "exp_no": "004",
    "recover": false,
    "config_path": "configfiles/asl2000/MViTv2_B_32x3/exp004.toml",
    "weight_path": "runs/asl1000/MViTv2_B_32x3/exp001/checkpoints/best.pth"
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl1000",
    "save_path": "runs/asl1000/MViTv2_B_32x3/exp001/checkpoints",
    "seed": 42,
    "exp_no": "001",
    "recover": true,
    "config_path": "configfiles/asl1000/MViTv2_B_32x3/exp001.toml",
    "weight_path": "runs/asl300/MViTv2_B_32x3/exp001/checkpoints/best.pth"
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl300",
    "save_path": "runs/asl300/MViTv2_B_32x3/exp001/checkpoints",
    "seed": 42,
    "exp_no": "001",
    "recover": true,
    "config_path": "configfiles/asl300/MViTv2_B_32x3/exp001.toml",
    "weight_path": "runs/asl100/MViTv2_B_32x3/exp008/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/S3D/exp079/checkpoints",
    "seed": 42,
    "exp_no": "079",
    "recover": true,
    "config_path": "configfiles/debug/test_sc.toml",
    "weight_path": null
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/MViTv2_B_32x3/exp008/checkpoints",
    "seed": 42,
    "exp_no": "008",
    "recover": false,
    "config_path": "configfiles/asl100/MViTv2_B_32x3/exp008.toml",
    "weight_path": null
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl2000",
    "save_path": "runs/asl2000/S3D/exp002/checkpoints",
    "seed": 42,
    "exp_no": "002",
    "recover": false,
    "config_path": "configfiles/asl2000/S3D/exp002.toml",
    "weight_path": "runs/asl1000/S3D/exp002/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl1000",
    "save_path": "runs/asl1000/S3D/exp002/checkpoints",
    "seed": 42,
    "exp_no": "002",
    "recover": false,
    "config_path": "configfiles/asl1000/S3D/exp002.toml",
    "weight_path": "runs/asl300/S3D/exp004/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl300",
    "save_path": "runs/asl300/S3D/exp004/checkpoints",
    "seed": 42,
    "exp_no": "004",
    "recover": false,
    "config_path": "configfiles/asl300/S3D/exp004.toml",
    "weight_path": "runs/asl100/S3D/exp076/checkpoints/best.pth"
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/S3D/exp076/checkpoints",
    "seed": 42,
    "exp_no": "076",
    "recover": false,
    "config_path": "configfiles/asl100/S3D/exp076.toml",
    "weight_path": null
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl2000",
    "save_path": "runs/asl2000/MViTv2_B_32x3/exp001/checkpoints",
    "seed": 42,
    "exp_no": "001",
    "recover": true,
    "config_path": "configfiles/asl2000/MViTv2_B_32x3/exp001.toml",
    "weight_path": null
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl2000",
    "save_path": "runs/asl2000/MViTv2_B_32x3/exp000/checkpoints",
    "seed": 42,
    "exp_no": "000",
    "recover": false,
    "config_path": "configfiles/asl2000/MViTv2_B_32x3/exp000.toml",
    "weight_path": "runs/asl1000/MViTv2_B_32x3/exp000/checkpoints/best.pth"
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl1000",
    "save_path": "runs/asl1000/MViTv2_B_32x3/exp000/checkpoints",
    "seed": 42,
    "exp_no": "000",
    "recover": false,
    "config_path": "configfiles/asl1000/MViTv2_B_32x3/exp000.toml",
    "weight_path": "runs/asl300/MViTv2_B_32x3/exp000/checkpoints/best.pth"
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl300",
    "save_path": "runs/asl300/MViTv2_B_32x3/exp000/checkpoints",
    "seed": 42,
    "exp_no": "000",
    "recover": false,
    "config_path": "configfiles/asl300/MViTv2_B_32x3/exp000.toml",
    "weight_path": "runs/asl100/MViTv2_B_32x3/exp007/checkpoints/best.pth"
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/MViTv2_B_32x3/exp007/checkpoints",
    "seed": 42,
    "exp_no": "007",
    "recover": false,
    "config_path": "configfiles/asl100/MViTv2_B_32x3/exp007.toml",
    "weight_path": null
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/MViTv2_B_32x3/exp004/checkpoints",
    "seed": 42,
    "exp_no": "004",
    "recover": false,
    "config_path": "configfiles/asl100/MViTv2_B_32x3/exp004.toml",
    "weight_path": null
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/S3D/exp061/checkpoints",
    "seed": 42,
    "exp_no": "061",
    "recover": false,
    "config_path": "configfiles/asl100/S3D/exp061.toml",
    "weight_path": null
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/S3D/exp062/checkpoints",
    "seed": 42,
    "exp_no": "062",
    "recover": false,
    "config_path": "configfiles/asl100/S3D/exp062.toml",
    "weight_path": null
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/S3D/exp059/checkpoints",
    "seed": 42,
    "exp_no": "059",
    "recover": false,
    "config_path": "configfiles/asl100/S3D/exp059.toml",
    "weight_path": null
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/S3D/exp058/checkpoints001",
    "seed": 42,
    "exp_no": "058",
    "recover": false,
    "config_path": "configfiles/asl100/S3D/exp058.toml",
    "weight_path": null
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/MViTv2_B_32x3/exp002/checkpoints",
    "seed": 42,
    "exp_no": "002",
    "recover": false,
    "config_path": "configfiles/asl100/MViTv2_B_32x3/exp002.toml",
    "weight_path": null
}

{
    "model": "MViTv2_B_32x3",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/MViTv2_B_32x3/exp001/checkpoints",
    "seed": 42,
    "exp_no": "001",
    "recover": false,
    "config_path": "configfiles/asl100/MViTv2_B_32x3/exp001.toml",
    "weight_path": null
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/S3D/exp057/checkpoints",
    "seed": 42,
    "exp_no": "057",
    "recover": false,
    "config_path": "configfiles/asl100/S3D/exp057.toml",
    "weight_path": null
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/S3D/exp048/checkpoints000",
    "seed": 42,
    "exp_no": "048",
    "recover": false,
    "config_path": "configfiles/asl100/S3D/exp048.toml",
    "weight_path": null
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/S3D/exp056/checkpoints",
    "seed": 42,
    "exp_no": "056",
    "recover": false,
    "config_path": "configfiles/asl100/S3D/exp056.toml",
    "weight_path": null
}

{
    "model": "S3D",
    "dataset": "WLASL",
    "split": "asl100",
    "save_path": "runs/asl100/S3D/exp055/checkpoints",
    "seed": 42,
    "exp_no": "055",
    "recover": false,
    "config_path": "configfiles/asl100/S3D/exp055.toml",
    "weight_path": null
}

29

## Now we can compare the runs

In [22]:
avail_acc_types = ["top_k_average_per_class_acc", "top_k_per_instance_acc"]
acc_type = avail_acc_types[1]
set_name = 'test'

#### Need to modify the names of S3D or they all get mixed together

In [23]:
df_format = []
for res in runs_16['results']: # + runs_32['results'] :
    model_name = res['admin']['model']
    if model_name == 'S3D':
        model_name += '_16'
    df_format.append(
        {'model': model_name, 'subset': res['admin']['split']} | {k : v for k, v in res['results'][set_name][acc_type].items()}
    )

for res in runs_32['results'] :
    model_name = res['admin']['model']
    if model_name == 'S3D':
        model_name += '_32'
    df_format.append(
        {'model': model_name, 'subset': res['admin']['split']} | {k : v for k, v in res['results'][set_name][acc_type].items()}
    )


df = pd.DataFrame(df_format)

In [24]:
df = df.rename(columns={"top1": "Top-1", "top5": "Top-5", "top10": "Top-10"})
# df

In [25]:
df['Top-1'] = df['Top-1'].apply(lambda x: f'{x*100:.2f}')
df['Top-5'] = df['Top-5'].apply(lambda x: f'{x*100:.2f}')
df['Top-10'] = df['Top-10'].apply(lambda x: f'{x*100:.2f}')

In [26]:
subsets = ['asl100', 'asl300', 'asl1000', 'asl2000']
for set_name in subsets:
    subdf = df[df['subset'] == set_name]
    print(f'{set_name}'.capitalize())
    display(subdf.sort_values('Top-1', ascending=False))

Asl100

            model  subset  Top-1  Top-5 Top-10
37  MViTv2_B_32x3  asl100  78.29  90.31  95.74
22  MViTv2_B_32x3  asl100  77.91  91.09  95.74
31  MViTv2_B_32x3  asl100  77.52  93.41  96.51
32  MViTv2_B_32x3  asl100  74.42  92.25  96.12
12  MViTv2_S_16x4  asl100  73.64  91.47  96.12
38  MViTv2_B_32x3  asl100  73.26  92.64  95.74
35         S3D_32  asl100  64.73  86.82  92.25
36         S3D_32  asl100  63.18  89.53  93.80
33         S3D_32  asl100  60.08  86.43  91.86
40         S3D_32  asl100  59.30  86.43  92.64
34         S3D_32  asl100  59.30  84.11  91.47
17         S3D_32  asl100  58.91  83.33  89.53
21         S3D_32  asl100  57.36  86.43  92.25
41         S3D_32  asl100  49.61  75.19  86.05
42         S3D_32  asl100  48.84  77.52  83.72
3          S3D_16  asl100  48.45  77.13  85.27
39         S3D_32  asl100  45.74  81.01  91.47
8          S3D_16  asl100  41.86  74.42  84.11
26         S3D_32  asl100  41.09  75.58  84.50
13  MViTv2_S_16x4  asl100   1.55   6.20  10.08

Asl300

            model  subset  Top-1  Top-5 Top-10
20  MViTv2_B_32x3  asl300  71.26  90.42  94.01
30  MViTv2_B_32x3  asl300  67.07  88.77  92.22
11  MViTv2_S_16x4  asl300  60.93  88.02  92.51
16         S3D_32  asl300  52.25  80.84  88.32
2          S3D_16  asl300  46.71  75.75  84.88
25         S3D_32  asl300  40.12  64.97  76.50
7          S3D_16  asl300  35.33  64.82  76.05

Asl1000

            model   subset  Top-1  Top-5 Top-10
19  MViTv2_B_32x3  asl1000  62.15  86.46  92.11
29  MViTv2_B_32x3  asl1000  56.77  83.48  89.66
10  MViTv2_S_16x4  asl1000  51.12  79.37  86.19
15         S3D_32  asl1000  44.56  74.47  83.26
1          S3D_16  asl1000  41.52  72.81  81.24
6          S3D_16  asl1000  30.38  59.97  70.58
24         S3D_32  asl1000  28.46  57.94  69.72

Asl2000

            model   subset  Top-1  Top-5 Top-10
18  MViTv2_B_32x3  asl2000  50.09  81.35  87.63
28  MViTv2_B_32x3  asl2000  44.56  76.35  83.71
9   MViTv2_S_16x4  asl2000  39.91  70.61  79.65
4   MViTv2_S_16x4  asl2000  37.65  69.36  80.38
14         S3D_32  asl2000  37.06  69.50  79.19
0          S3D_16  asl2000  33.83  66.69  76.00
23         S3D_32  asl2000  26.71  56.10  67.11
5          S3D_16  asl2000  23.38  51.23  64.19
27  MViTv2_B_32x3  asl2000   0.14   0.59   1.01